DROP TABLE IF EXISTS gatos;
DROP TABLE IF EXISTS users;
CREATE TABLE gatos(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(25) NOT NULL,
  sexo VARCHAR(1) NOT NULL
);

CREATE TABLE users(
  ID_KEY INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT(10) NOT NULL,
  USER_NAME VARCHAR(20) NOT NULL,
  USER_LAST_NAME VARCHAR(20) NOT NULL,
  USER_NIF VARCHAR (40) NOT NULL,
  REGISTRATION_DATE VARCHAR (40) NOT NULL
);

INSERT INTO gatos (nombre, sexo)
VALUES ('Miau', 'M');

INSERT INTO users (USER_ID, USER_NAME, USER_LAST_NAME, USER_NIF, REGISTRATION_DATE)
VALUES ('1', 'Pau', 'Serratosa Garrido', '53295343L', '21.10.2020');

INSERT INTO users (USER_ID, USER_NAME, USER_LAST_NAME, USER_NIF, REGISTRATION_DATE)
VALUES ('2', 'Maria', 'Monzó Tatjé', '53296748P', '22.10.2020')